---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  application:
    name: esercito-bianco
  config:
    activate:
      on-profile: bianco
  
---
spring:
  application:
    name: esercito-nero
  config:
    activate:
      on-profile: nero
