---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  application:
    name: esercito-bianco
  config:
    activate:
      on-profile: bianco
  
---
spring:
  application:
    name: esercito-nero
  config:
    activate:
      on-profile: nero

---
spring:
  profiles: bianco
esercito:
  forzaUomo: 6
  abilitaUomo: 5
  forzaElfo: 2
  abilitaElfo: 9
  forzaNano: 9
  abilitaNano: 2
  spada: 3
  arco: 2
  ascia: 1
  
---
spring:
  profiles: nero
esercito:
  forzaUomo: 6
  abilitaUomo: 5
  forzaElfo: 2
  abilitaElfo: 9
  forzaNano: 9
  abilitaNano: 2
  spada: 3
  arco: 2
  ascia: 1
