---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: bianco
  application:
    name: bianco
  
---
spring:
  profiles: nero
  application:
    name: nero
